- Contributors.md
Update contributions oneohthree
> Update contributions oneohthree

- Features.md
- scripts/backup_upgrade.sh
Upgrade the upgrade code and upgrade the docs
> Upgrade improve, fix #14

- CHANGELOG.md
- Features.md
- Makefile
- README.md
- TODO.md
- scripts/backup_upgrade.sh
- scripts/conf.sh
- scripts/deps.sh
- scripts/gen_cert.sh
- scripts/groups.sh
- scripts/install_mail.sh
- scripts/install_purge.sh
- scripts/provision.sh
- scripts/test_bind_dn.sh
- scripts/test_localhost.sh
- scripts/test_mailadmin.sh
- scripts/vmail_create.sh
- tests/README.md
- tests/test.sh
- tests/test_env.sh
- var/dovecot/conf.d/20-imap.conf
Support for Ubuntu Focal & Debian Buster
- Changed the location of the mailad.conf file, now it sits on /etc/mailad/
> Support for Focal and Buster

- CHANGELOG.md
- common.conf
- scripts/install_mail.sh
Split of the Debian and Ubuntu package list, as there are differences, this can lay down more work for other distros...
> Debian and Ubuntu have differences on some packages, ref #52

- CHANGELOG.md
- FAQ.md
- Makefile
- README.md
- scripts/test_localhost.sh
If no working DNS refuse to install spamassassin
> Make a test in the cheking process, for SPAMD updates, no working DNS and stop

- CHANGELOG.md
- common.conf
- mailad.conf
- scripts/provision.sh
- var/clamav-related/clamav_alternates.txt
> Make ClamAV mirrors selectable

- mailad.conf
- scripts/provision.sh
So far:
- Multiple mirrors
- Long timeout for slow/congested connections
> Fix some clamav-fresclam errors with the update

- CHANGELOG.md
- Features.md
- Makefile
- README.md
- TODO.md
- common.conf
- scripts/backup.sh
- scripts/custom_restore.sh
- scripts/restore.sh
Improve the backup and restore system
Almost all commits was marked as #69 by mistake.
My mistake, sorry
> Improve the backup and restore system

- CHANGELOG.md
- Features.md
- mailad.conf
- scripts/provision.sh
- scripts/test_localhost.sh
- var/postfix/main.cf
- var/postfix/master.cf
> Enable DNSBL

- CHANGELOG.md
- FAQ.md
- Features.md
- README.md
- common.conf
- mailad.conf
- scripts/provision.sh
- var/postfix/main.cf
- var/postfix/rules/command_filter.pcre
Add the activation and deactivation of the lines in master.cf, and general testing of the solution
> Fix Postscreen to enable DNSBL

- .all-contributorsrc
So in that way all files get updated at once.
> Add the translated README files in the processing of the contibutors

- CHANGELOG.md
- Makefile
- scripts/clamav_handle.sh
This with help the people with slow internet links
> Preserve ClamAV updates on upgrades and force-provision

- CHANGELOG.md
- var/dovecot-2.3/conf.d/90-quota.conf
- var/dovecot-2.3/scripts/quota-warning.sh
Fix the problem with the quota warning emails, also improved the mail content.
> Stdev pavelmc t122 fix quota warnings

- CHANGELOG.md
- README.md
- scripts/check_maildirs.sh
Fixes #132 
- Garbage collector script (monthly) was not upgrades to keep up with the last feature.
- Some other minor bug fixes.
> Fix the the garbage collector script

- CHANGELOG.md
- mailad.conf
Update clamav alternate mirror servers list
> Fixed clamav alternate mirror servers list

- CHANGELOG.md
- mailad.conf
Fixing #147 
Not working alternate mirrors
> Develop,  fixing #147 clamav alternate mirrors

- CHANGELOG.md
- common.conf
- mailad.conf
- scripts/test_bind_dn.sh
- scripts/test_localhost.sh
- scripts/test_mailadmin.sh
Feature request: handle multiple ADDC servers, closes #152
> Stdev pavelmc t152 multiple addc

- CHANGELOG.md
- Makefile
- README.md
- common.conf
- scripts/conf.sh
- scripts/deps.sh
- scripts/install_mail.sh
- scripts/install_purge.sh
- scripts/provision.sh
- scripts/test_bind_dn.sh
- scripts/test_localhost.sh
Give MailAD Debian bullseye support
> Stdev pavelmc t159 debian 11 bullseye support

- CHANGELOG.md
- scripts/groups.sh
- scripts/resume.sh
Groups daily emails will be generated only if there is a change on the groups.
> Stdev pavelmc t146 make alerts less verbose config

- CHANGELOG.md
- scripts/provision.sh
- scripts/test_localhost.sh
Fixing the logic and a typo that was causing a broken pipe error
> Bug #151 was not fixed completely

- CHANGELOG.md
- FAQ.md
- common.conf
- mailad.conf
- scripts/conf.sh
- scripts/deps.sh
- scripts/install_purge.sh
- scripts/provision.sh
- scripts/test_bind_dn.sh
- scripts/test_localhost.sh
> Improve LDAP cert handling in Debian

- CHANGELOG.md
- FAQ.md
- scripts/custom_restore.sh
- scripts/groups.sh
- scripts/test_localhost.sh
Fix this F*** problem for good.
> Fix Debian and PATH/sbin bug for good

- AD_Requirements.md
- Makefile
- README.md
- common.conf
- scripts/deps.sh
- scripts/install_mail.sh
- scripts/install_purge.sh
- tests/test.sh
- utils/README.md
- utils/samba_scaffold.sh
This PR will have the commits to bring MailAD support on Ubuntu 22.04 LTS
> Ubuntu 22.04 LTS Jammy Support

- AD_Requirements.md
- Makefile
- README.md
- common.conf
- scripts/deps.sh
- scripts/install_mail.sh
- scripts/install_purge.sh
- tests/test.sh
- utils/README.md
- utils/samba_scaffold.sh
> Merge develop into master

- CHANGELOG.md
- README.md
- scripts/check_maildirs.sh
> Stdev pavelmc t181 stalled mailboxes multiples dc

- FAQ.md
- i18n/AD_Requirements.es.md
- i18n/FAQ.es.md
Adding Spanish translation of AD_Requirements.md file
> 194_translate_ad_reqs

- .github/workflows/mailad-tests.yml
- .gitignore
- scripts/deps.sh
- scripts/install_purge.sh
- scripts/roundcube.sh
- scripts/snappy.sh
- tests/snappy_login.py
- tests/test_login.py
Using playwright to test the web server login
> First try with the snappy login schema
